





db_mysql:
	gcc -O2 -fPIC -shared -o db_mysql.so db_mysql.c \
	-I/usr/include/mysql -L/usr/lib64/mysql/ -lmysqlclient \
	-I/home/lighthouse/game/game/skynet/3rd/lua -L/home/lighthouse/game/game/skynet/3rd/lua -llua 










